name: Test
on:
  push:
    branches:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install deps
        uses: ./.github/actions/python-deps
      - name: Run Python tests
        run: |
          source ./venv/bin/activate
          pytest tests/