name: Python tests
on:
  pull_request:
    branches:
      - trunk
  push:
    branches-ignore:
      - release

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install deps
        uses: ./.github/actions/python-deps

      - name: Run Python tests
        uses: ./.github/actions/tests

