name: Test PR
on:
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install deps
        uses: ./.github/actions/python-deps

      - name: Run Python tests
        uses: ./.github/actions/tests
