name: release
on:
  push:
    branches:
      - release

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    # semantic release will skip outdated branch anyway, this will prevent from spending CI minutes on that
    concurrency:
      group: release
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install deps
        uses: ./.github/actions/python-deps
      # Semantic release
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: 'npm'
      - name: Install Node packages
        run: npm i
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --debug